name: CI Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.vscode/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # test for complexity. The GitHub editor is 127 chars wide
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          # Run pylint to catch other PEP8 errors
          pylint service tests --max-line-length=127

      - name: Run unit tests with PyTest
        run: |
          export FLASK_APP=service:app
          pytest --pspec --cov=service --cov-fail-under=95 --disable-warnings
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/testdb"

      # - name: Upload code coverage
      #   uses: codecov/codecov-action@v3.1.4
      
      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8
        uses: codecov/codecov-action@v4.1.1
        with:
          # Repository Codecov token. Used to authorize report uploads
          token: # optional
          # Specify the path to the Codecov YML
          codecov_yml_path: # optional
          # Override to specify the parent commit SHA
          commit_parent: # optional
          # Directory to search for coverage reports.
          directory: # optional
          # Disable file fixes to ignore common lines from coverage (e.g. blank lines or empty brackets)
          disable_file_fixes: # optional
          # Disable search for coverage files. This is helpful when specifying what files you want to upload with the --file option.
          disable_search: # optional
          # Disable setting safe directory. Set to true to disable.
          disable_safe_directory: # optional
          # Don't upload files to Codecov
          dry_run: # optional
          # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
          env_vars: # optional
          # Folders to exclude from search
          exclude: # optional
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: # optional
          # Path to coverage file to upload
          file: # optional
          # Comma-separated list of files to upload
          files: # optional
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: # optional
          # Override the git_service (e.g. github_enterprise)
          git_service: # optional
          # Raise no exceptions when no coverage reports found
          handle_no_reports_found: # optional
          # The job code
          job_code: # optional
          # User defined upload name. Visible in Codecov UI
          name: # optional
          # Override the assumed OS. Options are linux | macos | windows.
          os: # optional
          # Specify the branch name
          override_branch: # optional
          # Specify the build number
          override_build: # optional
          # The URL of the build where this is running
          override_build_url: # optional
          # Specify the commit SHA
          override_commit: # optional
          # Specify the pull request number
          override_pr: # optional
          # plugins to run. Options: xcode, gcov, pycoverage. The default behavior runs them all.
          plugin: # optional
          # Comma-separated list of plugins for use during upload.
          plugins: # optional
          # The code of the report. If unsure, do not include
          report_code: # optional
          # Used when not in git/hg project to identify project root directory
          root_dir: # optional
          # Specify the slug manually (Enterprise use)
          slug: # optional
          # Specify the base url to upload (Enterprise use)
          url: # optional
          # Use the legacy upload endpoint
          use_legacy_upload_endpoint: # optional
          # Specify whether the Codecov output should be verbose
          verbose: # optional
          # Specify which version of the Codecov CLI should be used. Defaults to `latest`
          version: # optional
          # Directory in which to execute codecov.sh
          working-directory: # optional
          
